---
baseurl: /games
githuburl: https://github.com/selassid/games/blob/gh-pages
collections:
  games:
      output: true
      permalink: :collection/:title:output_ext  # Permalink should use pretty title.
defaults:
  - scope:
      path: ""
      type: games
    values:
      layout: game
